### ISSUE TITLE
Add allowed_exceptions argument to multi_arrays

### ISSUE THREAD

**Issue by kylebarron** [cogeotiff/rio-tiler#263]
I tried updating my landsat [cogeo-mosaic-tiler fork](https://github.com/kylebarron/landsat-mosaic-tiler) to the latest `rio-tiler` and `rio-tiler-pds` (eventually moving to titiler, but not enough time right now).

Anyways, some tiles are erroring with "TileOutsideBands". As you know sometimes these exceptions are unavoidable in a mosaic situation. But the `L8Reader` [calls `multi_arrays`](https://github.com/cogeotiff/rio-tiler-pds/blob/ba0a868551690d4b56a87dac2572a374bd6190ba/rio_tiler_pds/landsat/aws/landsat8.py#L238-L246) and `multi_arrays` calls `filter_tasks` without the ability to set `allowed_exceptions`:
https://github.com/cogeotiff/rio-tiler/blob/a3d0d4bdb5b176e599996911effee2fd69b7cbd4/rio_tiler/tasks.py#L70-L71

**Comment by kylebarron** [comment]
I think here the issue is that there are two separate invocations of `filter_tasks`: one in the mosaic reader when you're combining multiple assets, but another in the `L8Reader` when you're potentially reading multiple bands at once. And I think it's that second one that's creating the `TileOutsideBounds` error?

**Comment by vincentsarago** [comment]
@kylebarron I'm not sure to understand because the mosaic_reader should allow `TileOutsideBounds`

https://github.com/cogeotiff/rio-tiler/blob/a3d0d4bdb5b176e599996911effee2fd69b7cbd4/rio_tiler/mosaic/reader.py#L83

The `L8Reader` doesn't allow it so it should raise the `TileOutsideBounds` exception but then it should be silenced in the mosaic_reader 🤷‍♂️

**Comment by kylebarron** [comment]
> The `L8Reader` doesn't allow it so it should raise the `TileOutsideBounds` exception but then it should be silenced in the mosaic_reader

I see what you're saying, but I'm not sure those errors are being caught. I'll try to make a better reproducible example later.

**Comment by kylebarron** [comment]
To reproduce:

```
from cogeo_mosaic.backends import MosaicBackend
from rio_tiler_pds.landsat.aws import L8Reader
from rio_tiler.mosaic.methods import FirstMethod

z, x, y = 10, 184, 402
url = 's3://tmp-us-west-2-kylebarron/tmp/mosaics/landsat/mosaic_2019_spring.json.gz'

with MosaicBackend(url, reader=L8Reader) as mosaic:
    (tile, mask), assets_used = mosaic.tile(x, y, z,
        pixel_selection=FirstMethod,
        tilesize=256,
        bands=('B4',),
        expression=None)
```

Exception:
```
INFO:root:Tile 10/184/402 is outside image bounds
Traceback (most recent call last):
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/rio_tiler/tasks.py", line 42, in filter_tasks
    yield future.result(), asset
  File "/Users/kyle/local/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/kyle/local/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/kyle/local/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/cogeo_mosaic/backends/base.py", line 109, in _reader
    return src_dst.tile(x, y, z, **kwargs)
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/rio_tiler_pds/landsat/aws/landsat8.py", line 245, in tile
    **kwargs,
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/rio_tiler/tasks.py", line 71, in multi_arrays
    data, masks = zip(*[r for r, _ in filter_tasks(tasks)])
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/rio_tiler/tasks.py", line 71, in <listcomp>
    data, masks = zip(*[r for r, _ in filter_tasks(tasks)])
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/rio_tiler/tasks.py", line 42, in filter_tasks
    yield future.result(), asset
  File "/Users/kyle/local/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/kyle/local/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/kyle/local/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/rio_tiler_pds/landsat/aws/landsat8.py", line 234, in _reader
    tile, mask = cog.tile(*args, **kwargs)
  File "/Users/kyle/local/anaconda3/lib/python3.7/site-packages/rio_tiler/io/cogeo.py", line 298, in tile
    "Tile {}/{}/{} is outside image bounds".format(tile_z, tile_x, tile_y)
rio_tiler.errors.TileOutsideBounds: Tile 10/184/402 is outside image bounds
```

**Comment by vincentsarago** [comment]
So on my laptop it's working fine. 

The `Exception` you are seeing are in fact `logs` (you can verify by priting tile or mask after the block). 

you can also turnoff the logging 

```python
import logging
from cogeo_mosaic.backends import MosaicBackend
from rio_tiler_pds.landsat.aws import L8Reader
from rio_tiler.mosaic.methods import FirstMethod

logger = logging.getLogger()
logger.setLevel(logging.CRITICAL)

z, x, y = 10, 184, 402 
url = 's3://tmp-us-west-2-kylebarron/tmp/mosaics/landsat/mosaic_2019_spring.json.gz' 
with MosaicBackend(url, reader=L8Reader) as mosaic: 
    (tile, mask), assets_used = mosaic.tile(x, y, z, 
        pixel_selection=FirstMethod, 
        tilesize=256, 
        bands=('B4',), 
        expression=None) 
```

**Comment by vincentsarago** [comment]
I'm going to closes this because we couldn't reproduce the problem locally! (and #266 might fix it 🤷‍♂️ )
