### ISSUE TITLE
nan in raster causes histogram stats to fail

### ISSUE THREAD

**Issue by scottstanie** [cogeotiff/rio-tiler#464]
I was running `rio-viz` to view a COG, and when I clicked the stats button, I got a error (though the app just kept the spinner wheel).

The relevant part is 

```python-traceback
File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/rio_tiler/io/cogeo.py", line 248, in stats
    stats = reader.stats(
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/rio_tiler/reader.py", line 405, in stats
    return {
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/rio_tiler/reader.py", line 406, in <dictcomp>
    f"{indexes[b]}": raster_stats(data[b], percentiles=percentiles, **hist_options)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/rio_tiler/utils.py", line 78, in _stats
    sample, edges = numpy.histogram(arr[~arr.mask], **kwargs)
  File "<__array_function__ internals>", line 5, in histogram
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/numpy/lib/histograms.py", line 793, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/numpy/lib/histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/numpy/lib/histograms.py", line 323, in _get_outer_edges
    raise ValueError(
ValueError: autodetected range of [nan, nan] is not finite
```

I believe this would be a fix in this repo, and not `rio-viz`, but let me know if that's not right.

Traceback:
<details>

```python-traceback
INFO:     127.0.0.1:56204 - "GET /stats?max_size=256 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/rio_viz/app.py", line 62, in dispatch
    response = await call_next(request)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 18, in __call__
    await responder(scope, receive, send)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 35, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/fastapi/routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/fastapi/routing.py", line 152, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/rio_viz/app.py", line 217, in stats
    return await src_dst.stats(
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/rio_viz/compat.py", line 56, in stats
    return await run_in_threadpool(self.dataset.stats, pmin, pmax, **kwargs)  # type: ignore
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/rio_tiler/io/cogeo.py", line 248, in stats
    stats = reader.stats(
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/rio_tiler/reader.py", line 405, in stats
    return {
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/rio_tiler/reader.py", line 406, in <dictcomp>
    f"{indexes[b]}": raster_stats(data[b], percentiles=percentiles, **hist_options)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/rio_tiler/utils.py", line 78, in _stats
    sample, edges = numpy.histogram(arr[~arr.mask], **kwargs)
  File "<__array_function__ internals>", line 5, in histogram
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/numpy/lib/histograms.py", line 793, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/numpy/lib/histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/Users/scott/opt/anaconda3/envs/mapping/lib/python3.8/site-packages/numpy/lib/histograms.py", line 323, in _get_outer_edges
    raise ValueError(
ValueError: autodetected range of [nan, nan] is not finite
```

</details>

**Comment by vincentsarago** [comment]
I believe this was fixed in the latest rio-tiler version (just release today). rio-viz will be updated in couple days. 
You can try using latest rio-viz (installed from GitHub source) or just with rio-tiler 3.0

```
pip install rio-tiler>=3.0
```

```python
from rio_tiler.io import COGReader

with COGReader("file") as dataset:
    stats = dataset.statistics()
```

if that doesn't work, please provide a like to your file 🙏

**Comment by scottstanie** [comment]
oh great timing! Thank you, and sorry for the lack of sample image
