### ISSUE TITLE
ModuleNotFoundError: No module named 'attr' error with 3.1.0

### ISSUE THREAD

**Issue by mhoeger** [cogeotiff/rio-tiler#486]
I get the following error with the latest version (3.1.0):

```
  | #17 23.92   Downloading rio-tiler-3.1.0.tar.gz (132 kB)
  | #17 24.12     ERROR: Command errored out with exit status 1:
  | #17 24.12      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a5nb4t0p/rio-tiler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a5nb4t0p/rio-tiler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-a5nb4t0p/rio-tiler/pip-egg-info
  | #17 24.12          cwd: /tmp/pip-install-a5nb4t0p/rio-tiler/
  | #17 24.12     Complete output (35 lines):
  | #17 24.12     Traceback (most recent call last):
  | #17 24.12       File "<string>", line 1, in <module>
  | #17 24.12       File "/tmp/pip-install-a5nb4t0p/rio-tiler/setup.py", line 42, in <module>
  | #17 24.12         setup(
  | #17 24.12       File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
  | #17 24.12         return distutils.core.setup(**attrs)
  | #17 24.12       File "/usr/lib/python3.8/distutils/core.py", line 121, in setup
  | #17 24.12         dist.parse_config_files()
  | #17 24.12       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 701, in parse_config_files
  | #17 24.12         parse_configuration(self, self.command_options,
  | #17 24.12       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 121, in parse_configuration
  | #17 24.12         meta.parse()
  | #17 24.12       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 426, in parse
  | #17 24.12         section_parser_method(section_options)
  | #17 24.12       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 399, in parse_section
  | #17 24.12         self[name] = value
  | #17 24.12       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 184, in __setitem__
  | #17 24.12         value = parser(value)
  | #17 24.12       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 515, in _parse_version
  | #17 24.12         version = self._parse_attr(value, self.package_dir)
  | #17 24.12       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 349, in _parse_attr
  | #17 24.12         module = import_module(module_name)
  | #17 24.12       File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
  | #17 24.12         return _bootstrap._gcd_import(name[level:], package, level)
  | #17 24.12       File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  | #17 24.12       File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  | #17 24.12       File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  | #17 24.12       File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  | #17 24.12       File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  | #17 24.12       File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  | #17 24.12       File "/tmp/pip-install-a5nb4t0p/rio-tiler/rio_tiler/__init__.py", line 3, in <module>
  | #17 24.12         from . import (  # noqa
  | #17 24.12       File "/tmp/pip-install-a5nb4t0p/rio-tiler/rio_tiler/colormap.py", line 8, in <module>
  | #17 24.12         import attr
  | #17 24.12     ModuleNotFoundError: No module named 'attr'
  | #17 24.12     ----------------------------------------
  | #17 24.46 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  | ------
```

3.0.3 seems ok though!

**Comment by vincentsarago** [comment]
👋 this is the same as https://github.com/cogeotiff/rio-cogeo/issues/228

please update your setuptools version `pip install setuptools -U`
