### ISSUE TITLE
Broadcast error with mosaic_reader past the bounds of a dataset 

### ISSUE THREAD

**Issue by samn** [cogeotiff/rio-tiler#500]
Hi :wave: 

It seems like attempting to build a mosaic with a bbox that extends beyond the bounds of a dataset creates an inconsistent data shape between datasets. I think this is happening because `WarpedVRT` reader doesn't support boundless reads, so the shape of the data is clipped to the dataset's bounds? I've worked around this by using a custom reader that uses `rasterio.wrap.reproject` after reading from the COG directly (instead of  reprojecting on the fly). 

I put together a short script demonstrating this issue with a couple of NAIP COGs from Planetary Computer:

```python
import rio_tiler

cog_urls = [
    'https://naipeuwest.blob.core.windows.net/naip/v002/ca/2020/ca_060cm_2020/35116/m_3511663_se_11_060_20200523.tif',
    'https://naipeuwest.blob.core.windows.net/naip/v002/ca/2020/ca_060cm_2020/35116/m_3511663_ne_11_060_20200523.tif',
]

bbox = [-116.15799958899584, 35.059243863202646, -116.15220014855299, 35.06651998829758]

def _reader(asset, *args, **kwargs):
  with rio_tiler.io.COGReader(asset) as cog:
    return cog.part(*args, **kwargs)

image_data, _assets = rio_tiler.mosaic.mosaic_reader(
    cog_urls,
    _reader,
    bbox,
)
```

<details><summary>COG & BBox Geometry</summary>

![Screenshot from 2022-07-12 10-55-44](https://user-images.githubusercontent.com/174850/178565075-c5d79e25-873d-4732-9d53-1f19f9202c42.png)

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.1522,
              35.059244
            ],
            [
              -116.158,
              35.059244
            ],
            [
              -116.158,
              35.06652
            ],
            [
              -116.1522,
              35.06652
            ],
            [
              -116.1522,
              35.059244
            ]
          ]
        ]
      },
      "properties": {
        "name": "read bounds",
        "fill": "green"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.122847,
              35.060229
            ],
            [
              -116.122135,
              35.126769
            ],
            [
              -116.189694,
              35.12724
            ],
            [
              -116.190352,
              35.060699
            ],
            [
              -116.122847,
              35.060229
            ]
          ]
        ]
      },
      "properties": {
        "cog url": "https://naipeuwest.blob.core.windows.net/naip/v002/ca/2020/ca_060cm_2020/35116/m_3511663_ne_11_060_20200523.tif"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -116.122792,
              34.997741
            ],
            [
              -116.12208,
              35.064281
            ],
            [
              -116.189654,
              35.064752
            ],
            [
              -116.19031,
              34.99821
            ],
            [
              -116.122792,
              34.997741
            ]
          ]
        ]
      },
      "properties": {
        "cog url": "https://naipeuwest.blob.core.windows.net/naip/v002/ca/2020/ca_060cm_2020/35116/m_3511663_se_11_060_20200523.tif"
      }
    }
  ]
}
```
</details

 Traceback:
```
Traceback (most recent call last):
  File "rio-tiler-boundless.py", line 15, in <module>
    image_data, _assets = rio_tiler.mosaic.mosaic_reader(
  File ".local/lib/python3.9/site-packages/rio_tiler/mosaic/reader.py", line 94, in mosaic_reader
    pixel_selection.feed(img.as_masked())
  File ".local/lib/python3.9/site-packages/rio_tiler/mosaic/methods/defaults.py", line 20, in feed
    pidex = self.tile.mask & ~tile.mask
ValueError: operands could not be broadcast together with shapes (4,1232,982) (4,1231,981) 
```

Not totally sure if I've understood the cause here correctly, or of how to fix this in rio-tiler, but I'm happy to contribute a fix with guidance if you're interested. Thanks!

**Comment by vincentsarago** [comment]
@samn The issue here is that when using `part`, rio-tiler create an array using the cog metadata and the given bounds, if there are slight difference in resolution for the 2 cog, the output array shape will be different for the 2 images and then the `mosaic reader` won't be able to merge the image.

Sadly I don't see any quick fix for this. In your application you'll need to first determine what the output shape will be before calling `part` (e.g you have the bbox, you need to define the output resolution you want and then you can set `width=, height=` in the part call). 


That's said there is maybe a bug in https://github.com/cogeotiff/rio-tiler/blob/62b0371836b0cb116a53459b5a79fcdc84f1cab1/rio_tiler/utils.py#L244-L321 because looking at the geo info from the 2 COG their resolution is the same! 

```
$ rio cogeo info https://naipeuwest.blob.core.windows.net/naip/v002/ca/2020/ca_060cm_2020/35116/m_3511663_se_11_060_20200523.tif --json | jq '.GEO'
{
  "CRS": "EPSG:26911",
  "BoundingBox": [
    573888,
    3873144,
    580050,
    3880524
  ],
  "Origin": [
    573888,
    3880524
  ],
  "Resolution": [
    0.6,
    -0.6
  ],
  "MinZoom": 12,
  "MaxZoom": 18
}

$ rio cogeo info https://naipeuwest.blob.core.windows.net/naip/v002/ca/2020/ca_060cm_2020/35116/m_3511663_ne_11_060_20200523.tif --json | jq '.GEO'
{
  "CRS": "EPSG:26911",
  "BoundingBox": [
    573828,
    3880074,
    579984,
    3887454
  ],
  "Origin": [
    573828,
    3887454
  ],
  "Resolution": [
    0.6,
    -0.6
  ],
  "MinZoom": 12,
  "MaxZoom": 18
}
```

**Comment by geospatial-jeff** [comment]
> because looking at the geo info from the 2 COG their resolution is the same!

The resolution in native CRS is the same but are slightly different after being projected to match the CRS of the bounding box (4326) when calculating height/width etc. for the VRT.  Both images are from the same quadrangle (ne/se) and there is latitudinal distortion projecting from NAD83 UTM to WGS84.  If the two images you've selected were east/west oriented (ex. ne/nw or se/sw) you probably wouldn't see this issue.

The resolutions of the two images (in degrees) after reprojection are:
```
5.909249718773602e-06
5.907606274181144e-06
```

Setting `width` and `height` should fix this; another workaround is to reproject the `bbox` to the native CRS of the image which will avoid the rounding error when reprojecting to WGS84:

```python
import rio_tiler
from rasterio.crs import CRS
from rasterio.warp import transform_bounds

cog_urls = [
    'https://naipeuwest.blob.core.windows.net/naip/v002/ca/2020/ca_060cm_2020/35116/m_3511663_se_11_060_20200523.tif',
    'https://naipeuwest.blob.core.windows.net/naip/v002/ca/2020/ca_060cm_2020/35116/m_3511663_ne_11_060_20200523.tif',
]

bbox = [-116.15799958899584, 35.059243863202646, -116.15220014855299, 35.06651998829758]
bbox26911 = transform_bounds(
    CRS.from_epsg(4326), CRS.from_epsg(26911), *bbox
)

def _reader(asset, *args, **kwargs):
  with rio_tiler.io.COGReader(asset) as cog:
    return cog.part(*args, **kwargs)

image_data, _assets = rio_tiler.mosaic.mosaic_reader(
    cog_urls,
    _reader,
    bbox26911,
    bounds_crs=CRS.from_epsg(26911),
)
```

**Comment by samn** [comment]
Ahhhh great find @geospatial-jeff. An explicit height/width definitely works for us.

Thanks for taking a look @vincentsarago & @geospatial-jeff! I'll close this issue since there's an easy workaround, and I do appreciate the help & explanation.

**Comment by lorenzori** [comment]
I am seeing the same error with COGs that have the same projection as that of the bounding box and have same resolution between them:

```
def window_reader(file, bbox) -> ImageData:
    with COGReader(file) as image:
        return image.part(bbox, bounds_crs=CRS.from_epsg(4326))

img, assets = mosaic_reader(
    rasters_list,
    window_reader,
    bbox=(-110.78,45.88,-110.73,45.9)
``` 

This will return the following error: 

```
ValueError: operands could not be broadcast together with shapes (4,3230,8075) (4,3428,8569) 
```

raised by 
```
/opt/conda/lib/python3.9/site-packages/rio_tiler/mosaic/methods/defaults.py in feed(self, tile)
     18         if self.tile is None:
     19             self.tile = tile
---> 20         pidex = self.tile.mask & ~tile.mask
```

If I re-project the rasters to 3857 the resolution in meters is identical so not sure what is going on. Any idea on what I could check? Unfortunately I can not share the images.

**Comment by lorenzori** [comment]
thanks @vincentsarago!

In the  [cogs.zip](https://github.com/cogeotiff/rio-tiler/files/9157232/cogs.zip) you have 2 "faux" COGs.

You can reproduce by running 
```
from rasterio.crs import CRS
from rio_tiler.io import COGReader
from rio_tiler.mosaic import mosaic_reader
from rio_tiler.models import ImageData

rasters_list = ['cog1_public.tif', 'cog2_public.tif']

def window_reader(file, bbox) -> ImageData:
    with COGReader(file) as image:
        return image.part(bbox, bounds_crs=CRS.from_epsg(4326))

# mosaic
img, assets = mosaic_reader(
    rasters_list,
    window_reader,
    bbox=(-110.86, 45.93, -110.83, 45.95)
)
```

**Comment by vincentsarago** [comment]
@lorenzori can you check that your 2 files have the same resolution because the one you share don't 

```python
with COGReader("cog1_public.tif") as cog1, COGReader("cog2_public.tif") as cog2:
    print(cog1.dataset.res)
    print(cog2.dataset.res)

>> (6.192047806054943e-06, 6.1920478060546355e-06)
>> (5.834668180893354e-06, 5.834668180894531e-06)
```

also your error message also indicate that there is a significant difference in resolution
> ValueError: operands could not be broadcast together with shapes (4,3230,8075) (4,3428,8569)

**Comment by lorenzori** [comment]
you are right, when I cropped the the tiles to share I messed with the resolution. Indeed if I project the originals to 3857 and assert they have the same resolution, the error from `mosaic_reader` disappears. Thank you!
